apiVersion: v1
kind: Service
metadata:
    name: authdb
    labels:
        app: authdb
spec:
    type: LoadBalancer
    ports:
        - port: 5432
          targetPort: authdb
    selector:
        app: authdb
