apiVersion: apps/v1
kind: Deployment
metadata:
    name: apigateway
spec:
    replicas: 1
    selector:
        matchLabels:
            app: apigateway
    template:
        metadata:
            labels:
                app: apigateway
        spec:
            containers:
                - name: apigateway
                  image: registry.me:5000/rafaeltab/kubetest/apigateway
                  imagePullPolicy: "Always"
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "200m"
                  ports:
                      - containerPort: 45000
                  env:
                      - name: MY_NODE_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: spec.nodeName
                      - name: MY_POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: MY_POD_NAMESPACE
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.namespace
                      - name: MY_POD_IP
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: MY_POD_SERVICE_ACCOUNT
                        valueFrom:
                            fieldRef:
                                fieldPath: spec.serviceAccountName
